export enum PermissionParameters
{
  ROLE_ACCESS_OPERATION_PROVIDER_NAME = 'R',
  ROLE_ACCESS_OPERATION_PERMISSION_TYPE_ROL_ACCESS_OPERATION = 13,
  ROLE_ACCESS_OPERATION_PERMISSION_TYPE_ORGANIZATION_ROLE =''
}
